### ISSUE TITLE
Demo program not working as shown

### ISSUE THREAD

**Issue by ruffk** [braddwalker/ZwiftPacketMonitor#16]
Brad

A call is needed to: RegistrationExtensions.AddZwiftPacketMonitoring(serviceCollection) otherwise things aren't initialized correctly.

I also think it would be nice to turn debug level logging on, especially for troubleshooting, so:

serviceCollection.AddLogging(configure => configure.AddConsole())
    .Configure<LoggerFilterOptions>(configure => configure.MinLevel = LogLevel.Debug);

RegistrationExtensions.AddZwiftPacketMonitoring(serviceCollection);

I have some other thoughts too if you'd like to make me a collaborator.

Thanks.

**Comment by braddwalker** [comment]
Good catch! I forgot to update the demo program after refactoring the DI stuff. Feel free to submit a PR for those (or any other) changes and I'm happy to take a look at them!

**Comment by ruffk** [comment]
Brad

I've made the fixes but cannot publish my branch as I don't have permission.  Can you help with that?

**Comment by braddwalker** [comment]
The first thing you'll need to do is to fork the repo. This will create a private copy of the repo for you. Then make your changes and push them up to your GitHub repo. Final step is to submit a pull request from your branch -> my main branch. Once that's done I'll be able to review your changes and approve/merge them.

**Comment by braddwalker** [comment]
Resolved with #18
